In [2]:
import numpy as np 

### Range

In [5]:
r = range(10)
print(r)

r = range(0,10, 2)
print(r)

r = range(10,0, -2)
print(r)

print(6 in range(10))
print(list(range(10)))

range(0, 10)
range(0, 10, 2)
range(10, 0, -2)
True
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


### Arange

In [18]:
arr = np.arange(0,10,2)
print(arr)

arr1 = np.arange(10,0,-1)
print(arr1)

arr2 = np.arange(0,10,.5)
print(arr2)

[0 2 4 6 8]
[10  9  8  7  6  5  4  3  2  1]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


### Linspace

In [20]:
l = np.linspace(0,10,5)
print(l)

l = np.linspace(1,10,10)
print(l)

l = np.linspace(1,10,10, endpoint = False)
print(l)

l,s= np.linspace(1,5,10, retstep = True)
print(l)
print(s)

[ 0.   2.5  5.   7.5 10. ]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1.  1.9 2.8 3.7 4.6 5.5 6.4 7.3 8.2 9.1]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
0.4444444444444444


### Logspace

In [22]:
arr = np.logspace(0,10,5)
print(arr)

arr = np.logspace(0,10,5, endpoint = False)
print(arr)

arr = np.logspace(0,10,5, base = 2)
print(arr)

[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10]
[1.e+00 1.e+02 1.e+04 1.e+06 1.e+08]
[1.00000000e+00 5.65685425e+00 3.20000000e+01 1.81019336e+02
 1.02400000e+03]
