### 1. Creation of Arrays and List

In [5]:
import numpy as np  

lst = [1, 3, 2]  
print(lst)  
print(type(lst))  
print('---')

arr = np.array([1, 2, 3])  
print(arr) 
print(type(arr))  
print('---')


print(arr == lst)
print('---')
print(arr.tolist() == lst)  # Converted array into list 
print(sorted(arr) == sorted(lst))  

[1, 3, 2]
<class 'list'>
---
[1 2 3]
<class 'numpy.ndarray'>
---
[ True False False]
---
False
True


### 2. Adding Elements in an Array vs List

In [8]:
lst = [1, 3, 2]  
print(lst) 
lst.append(4)  
print(lst)  
print('---')

arr = np.array([1, 2, 3]) 
print(arr)  
arr = np.append(arr, 4)  
print(arr)  

[1, 3, 2]
[1, 3, 2, 4]
---
[1 2 3]
[1 2 3 4]


### 3. Removing Elements in an Array vs List

In [14]:
lst = [1, 3, 2] 
print(lst)  
del lst[-2]  
print(lst) 
lst.pop()  # Removes the last Element
print(lst)
print('---')

arr = np.array([1, 2, 3]) 
print(arr)
arr = np.delete(arr, -2)  
print(arr)

[1, 3, 2]
[1, 2]
[1]
---
[1 2 3]
[1 3]


### 4. Updating Elements in an Arrays vs List 

In [17]:
lst = [1, 3, 2] 
print(lst)  
lst[-2] = 2  # Changing the second-to-last element (-2 index) to 2
lst[-1] = 3  # Changing the last element (-1 index) to 3
print(lst)  # Printing the updated list after modifications
print('---')

arr = np.array([1, 3, 2])  
print(arr) 
arr[-2] = 2  # Changing the second-to-last element (-2 index) to 2
arr[-1] = 3  # Changing the last element (-1 index) to 3
print(arr)  # Printing the updated NumPy array after modifications

[1, 3, 2]
[1, 2, 3]
---
[1 3 2]
[1 2 3]


### 5. Arrays Vs List Comparison

In [26]:
import time 

my_list = list(range(10000000))  


start_time = time.time() 
for _ in range(100):  
    if 5000000 in my_list:  
        pass
end_time = time.time()  
print('List : ', end_time - start_time) 

print('-'*30)

my_array = np.arange(10000000) 
start_time = time.time()  
for _ in range(100):  
    if 5000000 in my_array:  
        pass
end_time = time.time()  
print('Array : ', end_time - start_time) 

List :  6.6374571323394775
------------------------------
Array :  0.6822819709777832
