In [2]:
import numpy as np

### 1. Arithmetic Operations

In [5]:
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3],[4,5,6]])

print(a)
print(b)
print('-'*10)

# Addition
print(a + 2)
print(a + b)
print('-'*10)


# Subtract
print(a - 2)
print(a - b)
print('-'*10)

# Multiplication
print(a * 2)
print(a * b)
print('-'*10)

# Division
print(a / 2)
print(a / b)
print('-'*10)

# Exponential
print(a ** 2)
print(a ** b)
print('-'*10)

# Modulo
print(a % 2)
print(a % b)
print('-'*10)

[1 2 3]
[[1 2 3]
 [4 5 6]]
----------
[3 4 5]
[[2 4 6]
 [5 7 9]]
----------
[-1  0  1]
[[ 0  0  0]
 [-3 -3 -3]]
----------
[2 4 6]
[[ 1  4  9]
 [ 4 10 18]]
----------
[0.5 1.  1.5]
[[1.   1.   1.  ]
 [0.25 0.4  0.5 ]]
----------
[1 4 9]
[[  1   4  27]
 [  1  32 729]]
----------
[1 0 1]
[[0 0 0]
 [1 2 3]]
----------


### Comparison Operations

In [8]:
a = np.array([1,2,3])
b = np.array([[1, 2, 3],[4,5,6]])

print(a)
print(b)
print('-'*10)

# >
print(a > b)
print('-'*10)

# <
print(a < b)
print('-'*10)

# >=
print(a >= b)
print('-'*10)

# <=
print(a <= b)
print('-'*10)

# ==
print(a == b)
print('-'*10)

# !=
print(a != b)

[1 2 3]
[[1 2 3]
 [4 5 6]]
----------
[[False False False]
 [False False False]]
----------
[[False False False]
 [ True  True  True]]
----------
[[ True  True  True]
 [False False False]]
----------
[[ True  True  True]
 [ True  True  True]]
----------
[[ True  True  True]
 [False False False]]
----------
[[False False False]
 [ True  True  True]]


### Logical Operations 

In [11]:
a = np.array([1,2,3])
b = np.array([[1, 2, 3],[4,5,6]])
print(a)
print(b)

print('-'*10)

print(a & b)
print('-'*10)

print(a | b)
print('-'*10)

print(a ^ b)
print('-'*10)

[1 2 3]
[[1 2 3]
 [4 5 6]]
----------
[[1 2 3]
 [0 0 2]]
----------
[[1 2 3]
 [5 7 7]]
----------
[[0 0 0]
 [5 7 5]]
----------


### Bitwise Operations

In [15]:
a = np.array([1,2,3])
b = np.array([[1, 2, 3],[4,5,6]])

print(a)
print(b)
print('-'*10)

print(np.bitwise_and(a,b))

print(np.bitwise_or(a,b))

print(np.bitwise_xor(a,b))

print(np.bitwise_not(a,b))

print(np.right_shift(a,b))

print(np.left_shift(a,b))

[1 2 3]
[[1 2 3]
 [4 5 6]]
----------
[[1 2 3]
 [0 0 2]]
[[1 2 3]
 [5 7 7]]
[[0 0 0]
 [5 7 5]]
[[-2 -3 -4]
 [-2 -3 -4]]
[[0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]]
