In [2]:
import numpy as np

### 1. Converting Data Structures to Numpy Array

#### 1.1 Converting a Tuple to an array

In [8]:
tpl =(1,2,3 )
print(tpl)
print(type(tpl))

print("-"*30)

arr = np.array(tpl)
print(arr)
print(type(arr))

(1, 2, 3)
<class 'tuple'>
------------------------------
[1 2 3]
<class 'numpy.ndarray'>


#### 1.2 Converting a List to an array

In [12]:
lst =[1,2,3 ]
print(lst)
print(type(lst))

print("-"*30)

arr = np.array(lst)
print(arr)
print(type(arr))

[1, 2, 3]
<class 'list'>
------------------------------
[1 2 3]
<class 'numpy.ndarray'>


#### 1.3 Converting a List to an array

dct = {1 : 'apple' , 2 : 'orange' , 3 : 'cherry'}
print(dct)
print(type(dct))

print("-"*30)

arr = np.array(dct)
print(arr)
print(type(arr)) # But it's not the correct format 
print("-"*30)

arr_k = np.array(list(dct.keys()))
arr_v = np.array(list(dct.values()))

print(arr_k)
print(arr_v)

print(type(arr_k))
print(type(arr_v))


#### 1.4 Converting a Set to an array

In [34]:
set_ = {1,2,3}
print(lst)
print(type(lst))

print("-"*30)

arr = np.array(list(set_))
print(arr)
print(type(arr))

{1, 2, 3}
<class 'set'>
------------------------------
[1 2 3]
<class 'numpy.ndarray'>


#### 1.4 Converting String to an array

In [43]:
arr = np.array('Hello World')
print(arr)
print(type(arr)) # We can also do this 

# ELSE by converting it into the list 
print('-'*30)

arr = np.array(list('Hello World'))
print(arr)
print(type(arr))

Hello World
<class 'numpy.ndarray'>
------------------------------
['H' 'e' 'l' 'l' 'o' ' ' 'W' 'o' 'r' 'l' 'd']
<class 'numpy.ndarray'>


### 2. Converting the Datatypes of Numpy Array

#### 2.1 Create a Array of integers and then converting into other Datatypes 

In [52]:
arr = np.array([1,2,3,4,5])
print(arr)

print('-'*10)

arr_ = arr.astype('float')
print(arr_)

print('-'*10)

arr_ = arr.astype('str')
print(arr_)

print('-'*10)

arr_ = arr.astype('bool')
print(arr_)

[1 2 3 4 5]
----------
[1. 2. 3. 4. 5.]
----------
['1' '2' '3' '4' '5']
----------
[ True  True  True  True  True]


#### 2.1 Create a Array of Float and then converting into other Datatypes 

In [56]:
arr = np.array([1.,2.,3.,4.,5.])
print(arr)

print('-'*10)

arr_ = arr.astype('int')
print(arr_)

print('-'*10)

arr_ = arr.astype('str')
print(arr_)

print('-'*10)

arr_ = arr.astype('bool')
print(arr_)

[1. 2. 3. 4. 5.]
----------
[1 2 3 4 5]
----------
['1.0' '2.0' '3.0' '4.0' '5.0']
----------
[ True  True  True  True  True]


#### 2.1 Create a Array of String and then converting into other Datatypes 

In [60]:
arr = np.array(['1','2','3','4','5']) # Special Case - if the arr is like ['1','A','3','C','5']  it will not be converted other datatypes
print(arr)

print('-'*10)

arr_ = arr.astype('int')
print(arr_)

print('-'*10)

arr_ = arr.astype('float')
print(arr_)

print('-'*10)

arr_ = arr.astype('bool')
print(arr_)

['1' '2' '3' '4' '5']
----------
[1 2 3 4 5]
----------
[1. 2. 3. 4. 5.]
----------
[ True  True  True  True  True]


#### 2.1 Create a Array of Boolean and then converting into other Datatypes 

In [64]:
arr = np.array([True , False , False , False , True])
print(arr)

print('-'*10)

arr_ = arr.astype('int')
print(arr_)

print('-'*10)

arr_ = arr.astype('float')
print(arr_)

print('-'*10)

arr_ = arr.astype('str')
print(arr_)

[ True False False False  True]
----------
[1 0 0 0 1]
----------
[1. 0. 0. 0. 1.]
----------
['True' 'False' 'False' 'False' 'True']
