In [2]:
import numpy as np

### 1. Zeros

In [10]:
zeros_array = np.zeros(10)
print(zeros_array)
print('-----')

zeros_array = np.zeros((2, 4))
print(zeros_array)
print('-----')

zeros_array = np.zeros((2, 3, 4))
print(zeros_array)
print('-----')

zeros_array = np.zeros((2, 3), dtype = int)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
-----
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-----
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
-----
[[0 0 0]
 [0 0 0]]


### 2. Ones

In [13]:
ones_array = np.ones(10)
print(ones_array)
print('-----')

ones_array = np.ones((2, 4))
print(ones_array)
print('-----')

ones_array = np.ones((2, 3, 4))
print(ones_array)
print('-----')

ones_array = np.ones((2, 3), dtype = int)
print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
-----
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
-----
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
-----
[[1 1 1]
 [1 1 1]]


### 3. Eye

In [16]:
eye_array = np.eye(3)
print(eye_array)
print('-----')

eye_array = np.eye(3, 4)
print(eye_array)
print('-----')

eye_array = np.eye(3, 4, dtype = int)
print(eye_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-----
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
-----
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


#### Random Number Generator

In [20]:
print(np.random.rand())
print(np.random.rand(10))
print(np.random.rand(3, 3))

print(np.random.randint(100))
print(np.random.randint(100, size=10))
print(np.random.randint(100, size=(3, 3)))
print(np.random.randint(low=100, high=200, size=(3, 3)))

# Generate a random number from a normal distribution with mean 0 and standard deviation 1
print(np.random.randn())

# Generate a 2D array of 3x3 random numbers from a uniform distribution between 0 and 1
print(np.random.uniform(size=(3, 3)))

# Generate a 2D array of 3x3 random numbers from a binomial distribution with n=10 and p=0.5
print(np.random.binomial(10, 0.5, size=(3, 3)))

# Poisson ,Exponential, Gamma, Chi-squared, T-distribution, F-distribution Beta Log-normal Laplace

0.6774439239569519
[0.16899195 0.63775189 0.94891354 0.36110073 0.72224859 0.50633435
 0.06165025 0.4564642  0.99015425 0.60174237]
[[0.6497159  0.87302351 0.0859435 ]
 [0.39748316 0.56847212 0.68862512]
 [0.21601408 0.75449293 0.71765232]]
35
[95 24 47 66 54 90 84 20 36 16]
[[81 98 86]
 [83 17 47]
 [73 13 73]]
[[118 105 115]
 [154 173 188]
 [136 172 167]]
1.1627227591865164
[[0.8545722  0.07724576 0.75012176]
 [0.43941091 0.37344281 0.23044521]
 [0.75139823 0.52231853 0.16440845]]
[[3 6 2]
 [5 5 6]
 [7 5 4]]
