In [2]:
import numpy as np

### 1. Creating Multi-dimensional Arrays

##### 1.1 Create a 2D array from a list of lists

In [5]:
arr = np.array([[1,2,3] , [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


##### 1.2 Create a 3D array from a list of lists

In [7]:
arr = np.array([[[1,2,3] , [4,5,6] , [7,8,9]],
                [[10,11,12] , [13,14,15] , [16,17,18] ],
                [[19,20,21] , [22,23,24] , [25,26,27] ]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


##### 1.3 Create a 2D array from a list of tuples

In [9]:
arr = np.array([(1,2,3) , (4,5,6)])
print(arr)

[[1 2 3]
 [4 5 6]]


##### 1.4 Create a 2D array from a list of arrays

In [19]:
arr = np.array([np.array([1,2,3]) , np.array([4,5,6])])
print(arr)

[[1 2 3]
 [4 5 6]]


##### 1.5 Create a 2D array from a list of strings

In [22]:
arr = np.array([['1','2','3'] ,['4','5','6']])
print(arr)

[['1' '2' '3']
 ['4' '5' '6']]


##### 1.6 Create a 2D array from a list of dictionaries

In [25]:
arr = np.array([{'a' : 1 , 'b' : 2 , 'c' : 3} , {'d' : 4 , 'e' : 5 , 'f' : 6}])
print(arr)

[{'a': 1, 'b': 2, 'c': 3} {'d': 4, 'e': 5, 'f': 6}]


### 2. Finding details of an array 

#### 2.1 Print the shape of the array

In [29]:
arr = np.array([[1,2,3] , [4,5,6]])
print(arr.shape)

(2, 3)


#### 2.2 Print the number of dimension of the array

In [32]:
arr = np.array([[1,2,3] , [4,5,6]])
print(arr.ndim)

2


#### 2.3 Print the data type of the array 

In [37]:
arr = np.array([[1,2,3] , [4,5,6]])
print(arr.dtype)

int32


#### 2.4 Print the size of the array 

In [40]:
arr = np.array([[1,2,3] , [4,5,6]])
print(arr.size)

6


#### 2.5 Print the item | bytes taken by each element in an array

In [45]:
arr = np.array([[1,2,3] , [4,5,6]])
print(arr.itemsize)

4


#### 2.6 Print the type of the array

In [48]:
print(type(arr))

<class 'numpy.ndarray'>
